import type { MessageTemplate } from "./message-format";
import { MESSAGE_BANK_VOLUME } from "./messages/volume";
import { MESSAGE_BANK_GENERATED } from "./messages/generator";

/** Core templates — hand-audited respectful messages. */
const MESSAGE_BANK_CORE: MessageTemplate[] = [
  // —— MORNING / WAKE ——
  {
    id: "m01",
    area: "daily",
    slot: "morning",
    microAction: "Bed se uthte hi 1 glass paani",
    hinglish: "{name}, good morning ☀️ Naya din shuru ho raha hai — aaj ka pehla caring step: paani pijiye.",
    hindi: "{name}, सुप्रभात ☀️ नया दिन शुरू — पहला कदम: पानी पीजिए।",
    english: "{name}, good morning. Time to rise — your day starts with one glass of water.",
  },
  {
    id: "m02",
    area: "daily",
    slot: "morning",
    microAction: "Aaj ka 1 intention likho",
    hinglish: "{name}, naya din, nayi possibility. Aaj sirf ek intention likho — baaki follow karenge saath me.",
    hindi: "{name}, नया दिन, नई संभावना। आज एक इरादा लिखिए।",
    english: "{name}, new day, new possibility. Write one intention for today — we will walk with you.",
  },
  {
    id: "m03",
    area: "mind",
    slot: "morning",
    microAction: "2 min gratitude — 3 cheezein",
    hinglish: "{name}, subah ka mind fresh hota hai. 3 cheezein likho jinke liye thankful ho — energy shift hogi.",
    hindi: "{name}, सुबह का मन ताज़ा होता है। 3 चीज़ें लिखिए जिनके लिए आभारी हैं।",
    english: "{name}, mornings are powerful. List three things you are grateful for — it shifts your energy.",
  },
  {
    id: "m04",
    area: "health",
    slot: "morning",
    microAction: "5 min stretch ya walk",
    hinglish: "{name}, body ko on karo. 5 minute stretch — dimaag sharp, mood better. Chhota step, bada feel.",
    hindi: "{name}, शरीर को जगाइए। 5 मिनट स्ट्रेच — मन तेज़।",
    english: "{name}, wake your body up. Five minutes of stretch — sharper mind, better mood.",
  },
  {
    id: "m05",
    area: "career",
    slot: "morning",
    microAction: "Aaj ka #1 priority choose karo",
    hinglish: "{name}, office se pehle clarity. Aaj ka sabse important ek kaam choose karo — baaki noise baad me.",
    hindi: "{name}, काम से पहले स्पष्टता। आज का सबसे ज़रूरी एक काम चुनिए।",
    english: "{name}, before the chaos starts, pick today's single most important task.",
  },
  {
    id: "m06",
    area: "finance",
    slot: "morning",
    microAction: "₹20–50 side me rakho",
    hinglish: "{name}, subah ka money habit. Aaj ₹20 ya ₹50 side — EMI panic kam, control zyada.",
    hindi: "{name}, सुबह की बचत की आदत। आज ₹20-50 अलग रखिए।",
    english: "{name}, start the day with a money win. Set aside ₹20–50 — small habit, big control.",
  },
  {
    id: "m07",
    area: "love",
    slot: "morning",
    microAction: "Apne liye ek kind baat",
    hinglish: "{name}, dil ko subah se soft rakho. Aaj apne liye ek achhi baat bolo — mirror me ya journal me.",
    hindi: "{name}, दिल को नरम रखिए। आज अपने लिए एक अच्छी बात कहिए।",
    english: "{name}, be gentle with yourself this morning. Say one kind thing to yourself.",
  },
  {
    id: "m08",
    area: "family",
    slot: "morning",
    microAction: "Ghar walon ko good morning",
    hinglish: "{name}, ghar bhi tumhari responsibility hai par tum bhi important ho. Ek good morning message — connection badhega.",
    hindi: "{name}, घर भी ज़िम्मेदारी है पर आप भी महत्वपूर्ण हैं। एक अच्छा संदेश भेजिए।",
    english: "{name}, your family matters — and so do you. Send one warm good-morning message today.",
  },

  // —— MIDDAY / LUNCH ——
  {
    id: "d01",
    area: "health",
    slot: "midday",
    microAction: "Lunch break — phone side",
    hinglish: "{name}, lunch time. Khana khaya? Bina phone ke 15 min — body recharge, mind bhi.",
    hindi: "{name}, दोपहर का भोजन। खाया? बिना फोन 15 मिनट।",
    english: "{name}, lunch break. Eat without scrolling — fifteen minutes for your body.",
  },
  {
    id: "d02",
    area: "career",
    slot: "midday",
    microAction: "25 min deep work",
    hinglish: "{name}, dopahar ka focus block. 25 minute ek kaam — multitasking band, result aayega.",
    hindi: "{name}, दोपहर का फोकस। 25 मिनट एक काम।",
    english: "{name}, midday focus block. Twenty-five minutes on one task — no multitasking.",
  },
  {
    id: "d03",
    area: "finance",
    slot: "midday",
    microAction: "Ek unnecessary spend avoid",
    hinglish: "{name}, dopahar me ek impulse purchase postpone kar sakte hain — future aapko thank karega.",
    hindi: "{name}, आज एक फालतू खर्च टालिए।",
    english: "{name}, skip one impulse purchase today. Your future self will thank you.",
  },
  {
    id: "d04",
    area: "mind",
    slot: "midday",
    microAction: "5 min walk + paani",
    hinglish: "{name}, energy dip normal hai. 5 min walk, paani — wapas game me.",
    hindi: "{name}, थकान सामान्य है। 5 मिनट चलिए, पानी पीजिए।",
    english: "{name}, the afternoon dip is normal. Five-minute walk and water — back in the game.",
  },
  {
    id: "d05",
    area: "daily",
    slot: "midday",
    microAction: "Progress check — 1 line",
    hinglish: "{name}, half day ho gaya. Ek line likho: aaj kya achha hua? Hope banaye rakho.",
    hindi: "{name}, आधा दिन हो गया। एक पंक्ति: आज क्या अच्छा हुआ?",
    english: "{name}, half the day is done. Write one line: what went well so far?",
  },

  // —— AFTERNOON ——
  {
    id: "a01",
    area: "career",
    slot: "afternoon",
    microAction: "Ek email / task close karo",
    hinglish: "{name}, afternoon slump ke saath mat ladna — ek chhoti win le lo. Ek pending cheez finish.",
    hindi: "{name}, एक छोटी जीत लीजिए। एक काम पूरा करिए।",
    english: "{name}, beat the afternoon slump with a small win. Close one pending item.",
  },
  {
    id: "a02",
    area: "health",
    slot: "afternoon",
    microAction: "10 min walk",
    hinglish: "{name}, 10 minute walk = mind clear. Body online rakho — kal ka energy aaj se banta hai.",
    hindi: "{name}, 10 मिनट वॉक = साफ़ दिमाग।",
    english: "{name}, a ten-minute walk clears the mind. Today's movement is tomorrow's energy.",
  },
  {
    id: "a03",
    area: "finance",
    slot: "afternoon",
    microAction: "UPI / bill check 2 min",
    hinglish: "{name}, 2 minute money check. Koi bill due? Surprise se better prepared.",
    hindi: "{name}, 2 मिनट पैसों की जाँच।",
    english: "{name}, two-minute money check. Any bill due? Prepared beats surprised.",
  },
  {
    id: "a04",
    area: "love",
    slot: "afternoon",
    microAction: "Kisi ko thank you bolo",
    hinglish: "{name}, connection cure hai loneliness ka. Kisi ko thank you — chhota message, bada feel.",
    hindi: "{name}, किसी को धन्यवाद कहिए।",
    english: "{name}, connection heals loneliness. Thank someone today — a small message, a big feeling.",
  },
  {
    id: "a05",
    area: "family",
    slot: "afternoon",
    microAction: "5 min sirf apne liye",
    hinglish: "{name}, sab ke liye daudte ho. 5 minute sirf apne liye — guilt mat lo, zaroori hai.",
    hindi: "{name}, 5 मिनट सिर्फ अपने लिए।",
    english: "{name}, you run for everyone. Take five minutes just for you — without guilt.",
  },

  // —— EVENING / DINNER ——
  {
    id: "e01",
    area: "daily",
    slot: "evening",
    microAction: "Dinner mindfully",
    hinglish: "{name}, shaam ho gayi. Dinner peacefully — TV/phone band, khana taste karo. Body deserve karti hai.",
    hindi: "{name}, शाम हो गई। शांति से रात का खाना।",
    english: "{name}, evening wind-down. Eat dinner mindfully — no screens, just nourishment.",
  },
  {
    id: "e02",
    area: "mind",
    slot: "evening",
    microAction: "Phone 30 min side",
    hinglish: "{name}, raat ka overthink band karne ka time. Phone 30 min side — kal fresh mind.",
    hindi: "{name}, रात की चिंता रोकिए। फोन 30 मिनट दूर।",
    english: "{name}, stop feeding the night overthink. Phone aside for thirty minutes.",
  },
  {
    id: "e03",
    area: "career",
    slot: "evening",
    microAction: "Work shutdown ritual",
    hinglish: "{name}, kaam khatam ka signal do khud ko. Laptop band, kal ke list pe ek line — boundary strong.",
    hindi: "{name}, काम खत्म का संकेत दीजिए। लैपटॉप बंद।",
    english: "{name}, signal the end of work. Close the laptop — one line for tomorrow, then stop.",
  },
  {
    id: "e04",
    area: "health",
    slot: "evening",
    microAction: "Light walk post dinner",
    hinglish: "{name}, dinner ke baad 10 min walk — digestion + sleep dono better.",
    hindi: "{name}, खाने के बाद 10 मिनट टहलिए।",
    english: "{name}, ten minutes after dinner — better digestion and sleep.",
  },
  {
    id: "e05",
    area: "finance",
    slot: "evening",
    microAction: "Aaj ka kharcha note",
    hinglish: "{name}, raat ko guilt nahi, clarity. Aaj kitna spend — ek line note. Control wapas.",
    hindi: "{name}, आज का खर्च एक पंक्ति में लिखिए।",
    english: "{name}, clarity over guilt. Note today's spending in one line — control returns.",
  },
  {
    id: "e06",
    area: "love",
    slot: "evening",
    microAction: "Journal 3 feelings",
    hinglish: "{name}, dil bhaari ho to likhna shuru karo. 3 feelings — release = rise.",
    hindi: "{name}, 3 भावनाएँ लिखिए।",
    english: "{name}, if the heart is heavy, write three feelings. Release is how you rise.",
  },

  // —— NIGHT ——
  {
    id: "n01",
    area: "daily",
    slot: "night",
    microAction: "Kal ka 1 goal",
    hinglish: "{name}, sone se pehle — aaj proud feel karo. Kal ka ek goal soch lo. Hum kal phir milenge.",
    hindi: "{name}, सोने से पहले — आज पर गर्व। कल का एक लक्ष्य।",
    english: "{name}, before sleep — be proud of today. One goal for tomorrow. We will meet again.",
  },
  {
    id: "n02",
    area: "mind",
    slot: "night",
    microAction: "4-7-8 breathing",
    hinglish: "{name}, neend ke liye mind ko slow karo. 4-7-8 breathing — 3 round. Shant raat.",
    hindi: "{name}, 4-7-8 साँस — 3 बार।",
    english: "{name}, slow the mind for sleep. Try 4-7-8 breathing — three rounds.",
  },
  {
    id: "n03",
    area: "health",
    slot: "night",
    microAction: "Phone charging, bed ready",
    hinglish: "{name}, phone bed pe nahi. Charger pe, lights dim — body ko rest ka signal.",
    hindi: "{name}, फोन बिस्तर पर नहीं। चार्जर पर।",
    english: "{name}, phone off the bed. On the charger, lights dim — signal rest to your body.",
  },

  // —— ANY TIME — area specific depth ——
  {
    id: "x01",
    area: "finance",
    slot: "any",
    microAction: "EMI calendar check",
    hinglish: "{name}, EMI tension feel ho rahi hai? Aaram se calendar me due dates dekh lijiye — plan se sab manageable hota hai.",
    hindi: "{name}, EMI तनाव? कैलेंडर देखिए — योजना = शक्ति।",
    english: "{name}, EMI stress? Do not panic. Check due dates — a plan is power.",
  },
  {
    id: "x02",
    area: "finance",
    slot: "any",
    microAction: "Auto-debit ₹100",
    hinglish: "{name}, bachat boring nahi — future secure hai. ₹100 auto save setup socho.",
    hindi: "{name}, ₹100 ऑटो सेव की सोचिए।",
    english: "{name}, saving is not boring — it is security. Consider auto-saving ₹100.",
  },
  {
    id: "x03",
    area: "career",
    slot: "any",
    microAction: "No after 7pm email",
    hinglish: "{name}, burnout se bachne ke liye 7pm ke baad email band rakh sakte hain — aap insaan hain, rest zaroori hai.",
    hindi: "{name}, 7 बजे के बाद ईमेल नहीं।",
    english: "{name}, protect yourself from burnout. No emails after 7 PM — you are human.",
  },
  {
    id: "x04",
    area: "career",
    slot: "any",
    microAction: "Skill 15 min",
    hinglish: "{name}, career growth roz ke 15 min se. Aaj ek skill video ya article — invest in you.",
    hindi: "{name}, आज 15 मिनट सीखिए।",
    english: "{name}, career growth is daily. Fifteen minutes learning today — invest in you.",
  },
  {
    id: "x05",
    area: "love",
    slot: "any",
    microAction: "Self-love note",
    hinglish: "{name}, kisi aur ka wait kiye bina aaj apne liye ek kind note likh sakte hain — aap enough hain.",
    hindi: "{name}, आज अपने लिए एक नोट — आप पर्याप्त हैं।",
    english: "{name}, do not wait for someone else to make you feel valued. Write yourself a note today.",
  },
  {
    id: "x06",
    area: "love",
    slot: "any",
    microAction: "Old friend message",
    hinglish: "{name}, connection chahiye? Purane dost ko message — sharm mat, sab busy hain par sab lonely bhi.",
    hindi: "{name}, पुराने मित्र को संदेश भेजिए।",
    english: "{name}, need connection? Message an old friend — everyone is busy and lonely sometimes.",
  },
  {
    id: "x07",
    area: "health",
    slot: "any",
    microAction: "Medicine / vitamins",
    hinglish: "{name}, health wealth se pehle. Medicine / vitamins li? Body ka dhyaan = life ka dhyaan.",
    hindi: "{name}, दवा / विटामिन ली? शरीर = ज़िंदगी।",
    english: "{name}, health before wealth. Taken your medicine or vitamins? Caring for your body matters.",
  },
  {
    id: "x08",
    area: "health",
    slot: "any",
    microAction: "Gym / workout 20 min",
    hinglish: "{name}, gym ya ghar pe 20 min move. Sweat = stress out. Aaj ka body win.",
    hindi: "{name}, 20 मिनट व्यायाम। पसीना = तनाव बाहर।",
    english: "{name}, twenty minutes of movement — gym or home. Sweat the stress out.",
  },
  {
    id: "x09",
    area: "health",
    slot: "any",
    microAction: "Yoga 10 min",
    hinglish: "{name}, yoga 10 minute — breath + stretch. Mind shaant, body light.",
    hindi: "{name}, 10 मिनट योग।",
    english: "{name}, ten minutes of yoga — breath and stretch. Calm mind, light body.",
  },
  {
    id: "x10",
    area: "mind",
    slot: "any",
    microAction: "Worry box — 5 min",
    hinglish: "{name}, overthink? 5 min likho sab worries — phir box band. Kal dekhenge, aaj nahi.",
    hindi: "{name}, 5 मिनट चिंताएँ लिखिए — फिर बंद।",
    english: "{name}, overthinking? Write worries for five minutes — then close the box. Not tonight.",
  },
  {
    id: "x11",
    area: "mind",
    slot: "any",
    microAction: "Soft mode on",
    hinglish: "{name}, aaj heavy lag raha? Soft raho — kam pressure, zyada care. Hum saath hain.",
    hindi: "{name}, आज भारी है? नरम रहिए — हम साथ हैं।",
    english: "{name}, heavy day? Go soft — less pressure, more care. We are with you.",
  },
  {
    id: "x12",
    area: "family",
    slot: "any",
    microAction: "Family 10 min quality",
    hinglish: "{name}, ghar walon ke saath 10 min quality time — phone down, eyes on them.",
    hindi: "{name}, परिवार के साथ 10 मिनट — फोन दूर।",
    english: "{name}, ten minutes of quality family time — phone down, eyes on them.",
  },
  {
    id: "x13",
    area: "daily",
    slot: "any",
    microAction: "Smile — mirror me",
    hinglish: "{name}, chhoti si smile try karo. Science bolti hai — mood shift hota hai. Worth it.",
    hindi: "{name}, एक मुस्कान आजमाइए।",
    english: "{name}, try a small smile. Science says it shifts mood. Worth it.",
  },
  {
    id: "x14",
    area: "daily",
    slot: "any",
    microAction: "1 kind act",
    hinglish: "{name}, aaj kisi ki help — chhoti si. Duniya better, tum bhi better feel karoge.",
    hindi: "{name}, आज किसी की छोटी मदद।",
    english: "{name}, one small act of kindness today — the world and you both get better.",
  },
  {
    id: "x15",
    area: "finance",
    slot: "any",
    microAction: "No Swiggy today",
    hinglish: "{name}, aaj delivery skip — ghar ka khana ya simple. Paisa + health dono save.",
    hindi: "{name}, आज डिलीवरी छोड़िए।",
    english: "{name}, skip delivery today — home food or simple. Money and health both win.",
  },
  {
    id: "x16",
    area: "career",
    slot: "any",
    microAction: "Ask for help",
    hinglish: "{name}, akela mat carry karo load. Aaj ek colleague se help maango — strength hai weakness nahi.",
    hindi: "{name}, आज किसी से मदद माँगिए।",
    english: "{name}, do not carry everything alone. Ask a colleague for help today — strength, not weakness.",
  },
  {
    id: "x17",
    area: "love",
    slot: "any",
    microAction: "Boundary set",
    hinglish: "{name}, 'no' bolna seekho jahan zaroori ho. Dil ki protection = self respect.",
    hindi: "{name}, जहाँ ज़रूरी हो 'ना' कहिए।",
    english: "{name}, learn to say no where needed. Protecting your heart is self-respect.",
  },
  {
    id: "x18",
    area: "health",
    slot: "any",
    microAction: "Paani — 1 glass abhi",
    hinglish: "{name}, dehydration = tired mind. Abhi 1 glass paani — 30 second, instant upgrade.",
    hindi: "{name}, अभी एक गिलास पानी।",
    english: "{name}, dehydration dulls the mind. One glass of water right now — thirty seconds.",
  },
  {
    id: "x19",
    area: "mind",
    slot: "any",
    microAction: "Nature 5 min",
    hinglish: "{name}, balcony / window — 5 min hawa. Grounding se anxiety kam hoti hai.",
    hindi: "{name}, 5 मिनट बाहर की हवा।",
    english: "{name}, balcony or window — five minutes of air. Grounding reduces anxiety.",
  },
  {
    id: "x20",
    area: "family",
    slot: "any",
    microAction: "Maa/papa call",
    hinglish: "{name}, maa papa ko call? 2 minute — unka din ban jayega, tumhara bhi.",
    hindi: "{name}, माता-पिता को कॉल? 2 मिनट।",
    english: "{name}, call your parents? Two minutes — it makes their day and yours.",
  },
];

/** Every id unique — never repeat until customer has seen all matching pool. */
export const MESSAGE_BANK: MessageTemplate[] = [
  ...MESSAGE_BANK_CORE,
  ...MESSAGE_BANK_VOLUME,
  ...MESSAGE_BANK_GENERATED,
];

export function getMessageBankStats() {
  const byArea: Record<string, number> = {};
  const bySlot: Record<string, number> = {};
  for (const m of MESSAGE_BANK) {
    byArea[m.area] = (byArea[m.area] ?? 0) + 1;
    bySlot[m.slot] = (bySlot[m.slot] ?? 0) + 1;
  }
  return { total: MESSAGE_BANK.length, byArea, bySlot };
}

/** Bump when message content changes — triggers fresh daily pulses for existing users. */
export const MESSAGE_BANK_VERSION = String(getMessageBankStats().total);
